[package]
name = "shaders"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { git = "https://github.com/embarkstudios/rust-gpu" }
shared = { path = "../shared" }
